#!/bin/sh
set -eu
while read local_ref local_oid remote_ref remote_oid; do
  case "$local_oid" in 0000000000000000000000000000000000000000) continue ;; esac
  for revision in $(git rev-list "$local_oid"); do
    python3 ops/public_check.py --revision "$revision"
  done
done
